apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "radarr.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "radarr.labels" . | nindent 8 }}
      annotations:
        {{- if and .Values.persistence.enabled .Values.persistence.veleroSchedule }}
        backup.velero.io/backup-volumes: config
        {{- end }}
    spec:
      containers:
      - name: radarr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 7878
        env:
        - name: PUID
          value: {{ .Values.puid | quote }}
        - name: PGID
          value: {{ .Values.pgid | quote }}
        - name: TZ
          value: {{ .Values.timezone | quote }}
        volumeMounts:
        - name: movies
          mountPath: /movies
          readOnly: false
        - name: config
          mountPath: /config
          readOnly: false
        - name: downloads
          mountPath: /downloads
          readOnly: false
        - name: scripts
          mountPath: /scripts
          readOnly: false
      volumes:
      # any 1-off scripts will be stored here (so they can be available for radarr)
      - name: scripts
        configMap:
          name: {{ .Release.Name }}
      # radarr will look for downloaded movies in this folder
      - name: downloads
      {{- if .Values.volumes.downloads -}}
        {{ toYaml .Values.volumes.downloads | nindent 8 }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      # when radarr has detected a movie, it will be moved to this
      # directory for long-term storage
      - name: movies
      {{- if .Values.volumes.movies -}}
        {{ toYaml .Values.volumes.movies | nindent 8 }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: config
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      {{- else }}
        emptyDir: {}
      {{- end }}


