apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hassGoCoordinator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hassGoCoordinator.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "hassGoCoordinator.labels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: hass-go-coordinator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["-v", {{ .Values.logging.verbosity | quote }}]
        env:
        - name: TZ
          value: {{ .Values.timezone | quote }}
        - name: ENV_FILE
          value: "/secrets/.env"
        ports:
        - name: http
          containerPort: {{ .Values.config.server.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          failureThreshold: 18
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          failureThreshold: 18
          timeoutSeconds: 10
        resources:
          {{- toYaml .Values.resources | trim | nindent 10 }}
        volumeMounts:
        - name: secrets
          readOnly: true
          mountPath: "/secrets"
      volumes:
      - name: secrets
        secret:
          secretName: {{ .Release.Name }}
