apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hassGoCoordinator.labels" . | nindent 4 }}
data:
  .env: {{ include "secrets" . | b64enc | quote }}
