apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonosHTTPAPI.labels" . | nindent 4 }}
data:
  copy-files.sh: |
    #!/usr/bin/env sh
    set -x
    cp -R /config-files/. /config
