apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonosHTTPAPI.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sonosHTTPAPI.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "sonosHTTPAPI.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      initContainers:
      - name: copy-configs
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "/config-files/copy-files.sh"]
        volumeMounts:
        - name: config
          mountPath: /config
        - name: config-files
          mountPath: /config-files
      containers:
      - name: node-sonos-http-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: sonos-http-api
          containerPort: 5005
        resources:
          {{- toYaml .Values.resources | trim | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: false
      volumes:
      - name: config
        emptyDir: {}
      - name: config-files
        configMap:
          name: {{ .Release.Name }}-configs
