replicaCount: 1
puid: 0
pgid: 0
timezone: America/New_York

volumes:
  tv: {}
    # nfs:
    #   server: 1.1.1.1
    #   path: /volume1/tv

  movies: {}
    # nfs:
    #   server: 1.1.1.1
    #   path: /volume1/movies

  config: {}
    # nfs:
    #   server: 1.1.1.1
    #   path: /volume1/config

image:
  repository: linuxserver/bazarr
  pullPolicy: IfNotPresent
  tag: version-v0.9.0.8

service:
  type: ClusterIP
  ports:
    http: 6767

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - chart-example.local
  tls: {}
  # - secretName: chart-example-tls
  #   hosts:
  #   - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
