apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
data:
  copy-files.sh: |
    #!/usr/bin/env sh
    set -x
    cp -R /config-files/. /config

  ServerConfig.json: |
    {
      "Port": 9117,
      "AllowExternal": {{ .Values.config.allowExternal }},
      "APIKey": {{ .Values.config.apiKey | quote }},
      "AdminPassword": {{ .Values.config.adminPassword | quote }},
      "InstanceId": {{ .Values.config.instanceID | quote }},
      "BlackholeDir": {{ .Values.config.blackholeDir | quote }},
      "UpdateDisabled": {{ .Values.config.updateDisabled }},
      "UpdatePrerelease": {{ .Values.config.updatePrerelease }},
      "BasePathOverride": {{ .Values.config.basePathOverride | quote }},
      "OmdbApiKey": {{ .Values.config.omdb.apiKey | quote }},
      "OmdbApiUrl": {{ .Values.config.omdb.apiUrl | quote }},
      "ProxyUrl": {{ .Values.config.proxy.url | quote }},
      "ProxyType": {{ .Values.config.proxy.type }},
      "ProxyPort": {{ .Values.config.proxy.port }},
      "ProxyUsername": {{ .Values.config.proxy.username | quote }},
      "ProxyPassword": {{ .Values.config.proxy.password | quote }},
      "ProxyIsAnonymous": {{ .Values.config.proxy.isAnonymous }}
    }
