kind: pipeline
type: kubernetes
name: default

workspace:
  base: /helm-charts

platform:
  os: linux
  arch: amd64

volumes:
- name: charts
  temp: {}

steps:
- name: lint
  image: alpine/helm:latest
  commands:
  - helm version
  - sh ./lint-charts.sh

- name: build
  image: alpine/helm:latest
  environment:
    OUTPUT_DIRECTORY: /charts
  commands:
  - helm version
  - sh ./build-charts.sh
  volumes:
  - name: charts
    path: /charts

- name: deploy
  image: amazon/aws-cli
  environment:
    AWS_DEFAULT_REGION:
      from_secret: aws-default-region
    AWS_ACCESS_KEY_ID:
      from_secret: aws-access-key-id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws-secret-access-key
  commands:
  - aws s3 cp /charts/ s3://helm.carldanley.com/ --recursive
  volumes:
  - name: charts
    path: /charts
