apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "qbittorrent.labels" . | nindent 8 }}
      annotations:
        {{- if and .Values.persistence.enabled .Values.persistence.veleroSchedule.enabled }}
        backup.velero.io/backup-volumes: qbittorrent-config
        {{- end }}
    spec:
      containers:
      - name: qbittorrent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
        - name: incoming-tcp
          containerPort: 6881
          protocol: TCP
        - name: incoming-udp
          containerPort: 6881
          protocol: UDP
        env:
        - name: PUID
          value: {{ .Values.puid | quote }}
        - name: PGID
          value: {{ .Values.pgid | quote }}
        - name: TZ
          value: {{ .Values.timezone | quote }}
        resources:
          {{- toYaml .Values.resources | trim | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: false
        - name: qbittorrent-state
          mountPath: /config/state
          readOnly: false
        - name: downloads
          mountPath: /downloads
          readOnly: false
      volumes:
      - name: downloads
        {{- if .Values.downloadVolume }}
{{ toYaml .Values.downloadVolume | indent 8 }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: config
        emptyDir: {}
      - name: qbittorrent-state
        emptyDir: {}
