replicaCount: 1

mosquitto:
  # filled with: admin:admin
  credentials: |
    admin:$6$VzopJ0P7FiPgkQOV$Zs76ceIjeG999fN3DR7xsl5jP7CgVlRLLp576Jg/5dcYORS90HNIOX66WnALeuXjNVbTI+ZdD8FvKXI6Ec42tw==

image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  tag: "1.6.10"

persistence:
  enabled: false
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  size: 10Mi
  veleroSchedule:
    enabled: true
    schedule: "0 */6 * * *"
    ttl: "168h"
    includedNamespaces: []

service:
  type: ClusterIP
  http:
    port: 1883

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
