apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deluge.labels" . | nindent 4 }}
data:
  copy-files.sh: |
    #!/usr/bin/env sh
    set -x
    cp -R /config-files/. /config

  web.conf: |
    {
      "file": 2,
      "format": 1
    }{
        "base": "/",
        "cert": "ssl/daemon.cert",
        "default_daemon": "",
        "enabled_plugins": ["labels"],
        "first_login": false,
        "https": false,
        "interface": "0.0.0.0",
        "language": "",
        "pkey": "ssl/daemon.pkey",
        "port": 8112,
        "pwd_salt": "95c23b8ace69e7a7183bcd656d1415581308a754",
        "pwd_sha1": "ecf25b988ffbf02b5fc5d97ae936e1f0aa5d3c93",
        "session_timeout": 3600,
        "sessions": {},
        "show_session_speed": false,
        "show_sidebar": {{ .Values.config.sidebar.show }},
        "sidebar_multiple_filters": true,
        "sidebar_show_zero": false,
        "theme": "gray"
    }

  core.conf: |
    {
      "file": 1,
      "format": 1
    }{
        "add_paused": false,
        "allow_remote": false,
        "auto_manage_prefer_seeds": false,
        "auto_managed": true,
        "cache_expiry": 60,
        "cache_size": 512,
        "copy_torrent_file": false,
        "daemon_port": 58846,
        "del_copy_torrent_file": false,
        "dht": true,
        "dont_count_slow_torrents": false,
        "download_location": "/root/Downloads",
        "download_location_paths_list": [],
        "enabled_plugins": ["labels"],
        "enc_in_policy": 1,
        "enc_level": 2,
        "enc_out_policy": 1,
        "geoip_db_location": "/usr/share/GeoIP/GeoIP.dat",
        "ignore_limits_on_local_network": true,
        "info_sent": 0.0,
        "listen_interface": "",
        "listen_ports": [
            6881,
            6891
        ],
        "listen_random_port": 61192,
        "listen_reuse_port": true,
        "listen_use_sys_port": false,
        "lsd": true,
        "max_active_downloading": {{ .Values.config.maxActiveDownloading }},
        "max_active_limit": {{ .Values.config.maxActiveLimit }},
        "max_active_seeding": {{ .Values.config.maxActiveSeeding }},
        "max_connections_global": {{ .Values.config.maxConnectionsGlobal }},
        "max_connections_per_second": {{ .Values.config.maxConnectionsPerSecond }},
        "max_connections_per_torrent": {{ .Values.config.maxConnectionsPerTorrent }},
        "max_download_speed": {{ .Values.config.maxDownloadSpeed }},
        "max_download_speed_per_torrent": {{ .Values.config.maxDownloadSpeedPerTorrent }},
        "max_half_open_connections": {{ .Values.config.maxHalfOpenConnections }},
        "max_upload_slots_global": {{ .Values.config.maxUploadSlotsGlobal }},
        "max_upload_slots_per_torrent": {{ .Values.config.maxUploadSlotsPerTorrent }},
        "max_upload_speed": {{ .Values.config.maxUploadSpeed }},
        "max_upload_speed_per_torrent": {{ .Values.config.maxUploadSpeedPerTorrent }},
        "move_completed": {{ .Values.config.moveCompleted }},
        "move_completed_path": "/root/Downloads",
        "move_completed_paths_list": [],
        "natpmp": true,
        "new_release_check": false,
        "outgoing_interface": "",
        "outgoing_ports": [
            0,
            0
        ],
        "path_chooser_accelerator_string": "Tab",
        "path_chooser_auto_complete_enabled": true,
        "path_chooser_max_popup_rows": 20,
        "path_chooser_show_chooser_button_on_localhost": true,
        "path_chooser_show_hidden_files": false,
        "peer_tos": "0x00",
        "plugins_location": "/config/plugins",
        "pre_allocate_storage": false,
        "prioritize_first_last_pieces": false,
        "proxy": {
            "anonymous_mode": {{ .Values.config.proxy.anonymousMode }},
            "force_proxy": {{ .Values.config.proxy.forceProxy }},
            "hostname": {{ .Values.config.proxy.hostname | quote }},
            "password": {{ .Values.config.proxy.password | quote}},
            "port": {{ .Values.config.proxy.port }},
            "proxy_hostnames": {{ .Values.config.proxy.proxyHostNames }},
            "proxy_peer_connections": {{ .Values.config.proxy.proxyPeerConnections }},
            "proxy_tracker_connections": {{ .Values.config.proxy.proxyTrackerConnections }},
            "type": {{ .Values.config.proxy.type }},
            "username": {{ .Values.config.proxy.username | quote }}
        },
        "queue_new_to_top": {{ .Values.config.queueNewToTop }},
        "random_outgoing_ports": true,
        "random_port": true,
        "rate_limit_ip_overhead": true,
        "remove_seed_at_ratio": false,
        "seed_time_limit": 180,
        "seed_time_ratio_limit": 7.0,
        "send_info": false,
        "sequential_download": false,
        "share_ratio_limit": 2.0,
        "shared": false,
        "stop_seed_at_ratio": false,
        "stop_seed_ratio": 2.0,
        "super_seeding": false,
        "torrentfiles_location": "/root/Downloads",
        "upnp": true,
        "utpex": true
    }

  auth: |
    localclient:5b7ca04c8ab6f35b662e5891e3885c53cc7882c8:10

  hostlist.conf: |
    {
      "file": 3,
      "format": 1
    }{
        "hosts": [
            [
                "0ff81a6c9dd14658895d3f27affdc3ee",
                "127.0.0.1",
                58846,
                "localclient",
                "5b7ca04c8ab6f35b662e5891e3885c53cc7882c8"
            ]
        ]
    }
