{{- if and .Values.persistence.enabled .Values.persistence.veleroSchedule -}}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deluge.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.persistence.veleroSchedule.schedule | quote }}
  template:
    ttl: {{ .Values.persistence.veleroSchedule.ttl | quote }}
    includedNamespaces:
    {{- toYaml .Values.persistence.veleroSchedule.includedNamespaces | indent 4 }}
    labelSelector:
      matchLabels:
        {{- include "deluge.selectorLabels" . | nindent 8 }}
{{- end }}

