{{- $dot := . -}}
{{- range $key, $value := .Values.services }}
{{- if and $value.enabled $value.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ $dot.Release.Name }}-{{ $key }}"
  namespace: {{ $dot.Release.Namespace }}
  labels:
    app: synology
    service: {{ $key | quote }}
  {{- with $value.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.ingress.tls }}
  tls:
  {{- range $value.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range $value.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: {{ $value.ingress.path }}
        backend:
          serviceName: "{{ $dot.Release.Name }}-{{ $key }}"
          servicePort: {{ $value.service.port }}
  {{- end }}
{{- end }}
{{- end }}
