{{- if .Values.plex.enabled -}}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-plex
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
subsets:
- addresses:
  - ip: {{ .Values.synologyIP | quote }}
  ports:
  - port: {{ .Values.plex.service.port }}
    name: plex
    protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-plex
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.plex.service.type }}
  ports:
  - port: {{ .Values.plex.service.port }}
    name: plex
    protocol: TCP
{{- end }}
