apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "sonarr.labels" . | nindent 8 }}
      annotations:
        {{- if and .Values.persistence.enabled .Values.persistence.veleroSchedule }}
        backup.velero.io/backup-volumes: config
        {{- end }}
    spec:
      containers:
      - name: sonarr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8989
        env:
        - name: PUID
          value: {{ .Values.puid | quote }}
        - name: PGID
          value: {{ .Values.pgid | quote }}
        - name: TZ
          value: {{ .Values.timezone | quote }}
        volumeMounts:
        - name: shows
          mountPath: /tv
          readOnly: false
        - name: config
          mountPath: /config
          readOnly: false
        - name: downloads
          mountPath: /downloads
          readOnly: false
      volumes:
      # sonarr will look for downloaded shows in this folder
      - name: downloads
      {{- if .Values.volumes.downloads -}}
        {{ toYaml .Values.volumes.downloads | nindent 8 }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      # when sonarr has detected a show, it will be moved to this
      # directory for long-term storage
      - name: shows
      {{- if .Values.volumes.shows -}}
        {{ toYaml .Values.volumes.shows | nindent 8 }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: config
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      {{- else }}
        emptyDir: {}
      {{- end }}


