replicaCount: 1
puid: 0
pgid: 0
timezone: America/New_York

downloadVolume: {}
  # nfs:
  #   server: 1.1.1.1
  #   path: /volume1/downloads

image:
  repository: linuxserver/qbittorrent
  pullPolicy: IfNotPresent
  tag: 4.3.0202008030943-7033-8ff4374ubuntu18.04.1-ls72

persistence:
  enabled: false
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  size: 10Mi
  veleroSchedule:
    enabled: true
    veleroNamespace: "velero"
    schedule: "0 */6 * * *"
    ttl: "168h"
    includedNamespaces: []

service:
  type: ClusterIP
  ports:
    http: 8080
    incomingTCP: 6881
    incomingUDP: 6881

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - chart-example.local
  tls: {}
  # - secretName: chart-example-tls
  #   hosts:
  #   - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
