apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.ports.http }}
    targetPort: http
  - name: incoming-tcp
    port: {{ .Values.service.ports.incomingTCP }}
    targetPort: incoming-tcp
    protocol: TCP
  - name: incoming-udp
    port: {{ .Values.service.ports.incomingUDP }}
    targetPort: incoming-udp
    protocol: UDP
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
