apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drone.server.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.drone.rpcSecret | base64 | quote }}
  database-datasource: {{ .Values.drone.server.database.connectionString | base64 | quote }}
  github-client-id: {{ .Values.drone.server.github.clientId | base64 | quote }}
  github-client-secret: {{ .Values.drone.server.github.clientSecret | base64 | quote }}
