apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  copy-files.sh: |
    #!/usr/bin/env sh
    set -x
    cp -R /config-files/. /config

  mosquitto.conf: |
    password_file: /mosquitto/config/password-file.conf
    {{- if .Values.persistence.enabled -}}
    persistence true
    persistence_location /mosquitto/data
    {{- end }}

  password-file.conf: |
    {{ .Values.mosquitto.username }}:{{ .Values.mosquitto.password }}
