apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  copy-files.sh: |
    #!/usr/bin/env sh
    set -x
    cp -R /config-files/. /config

  mosquitto.conf: |
    allow_anonymous false
    password_file /mosquitto/config/credentials
    {{- if .Values.persistence.enabled -}}
    persistence true
    persistence_location /mosquitto/data
    {{- end }}

  credentials: {{ .Values.mosquitto.credentials | quote }}
