apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homeAssistant.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "homeAssistant.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "homeAssistant.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: git-sync
        image: "{{ .Values.gitSync.image.repository }}:{{ .Values.gitSync.image.tag }}"
        imagePullPolicy: {{ .Values.gitSync.image.pullPolicy }}
        command: ['sh', '-c', '[ "$(ls /config)" ] || git clone {{ .Values.gitSync.repository }} /config']
        volumeMounts:
        - name: config
          mountPath: /config
        - name: git-credentials
          mountPath: /root/.ssh
      - name: copy-secrets
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ['cp', '/homeassistant-secrets/secrets.yaml', '/config']
        volumeMounts:
        - name: config
          mountPath: /config
        - name: homeassistant-secrets
          mountPath: /homeassistant-secrets
      containers:
      - name: homeassistant
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8123
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          failureThreshold: 18
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          failureThreshold: 18
          timeoutSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          {{- toYaml .Values.resources | trim | nindent 10 }}
      volumes:
      - name: config
        emptyDir: {}
      - name: git-credentials
        secret:
          defaultMode: 256
          secretName: {{ .Release.Name }}-git-credentials
      - name: homeassistant-secrets
        secret:
          defaultMode: 256
          secretName: {{ .Release.Name }}-homeassistant-secrets
          items:
          - key: secrets.yaml
            path: secrets.yaml
