apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homeAssistant.labels" . | nindent 4 }}
data:
  id_rsa: {{ .Values.gitSync.ssh.privateKey | b64enc | quote }}
