apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-git-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homeAssistant.labels" . | nindent 4 }}
data:
  config: {{ .Values.gitSync.ssh.config | b64enc | quote }}
  id_rsa: {{ .Values.gitSync.ssh.privateKey | b64enc | quote }}
