apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-homeassistant-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homeAssistant.labels" . | nindent 4 }}
data:
  secrets.yaml: {{ .Values.homeassistant.secrets | toYaml | b64enc | quote }}
